<a href="https://colab.research.google.com/github/baubyte/CienciaDeDatos/blob/main/Introducci%C3%B3n_a_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a NumPy
## Modulo 2
## Objetivo
Comprender cómo trabajar con estructuras numéricas eficientes para análisis de datos.

## ¿QUÉ ES NUMPY?
 Es la biblioteca fundamental para el computo numerico en Python, que proporciona soporte para arreglos multidimensionales y funciones matemáticas optimizadas.
 En Ciencia de Datos es muy común trabajar con:
- vectores de datos
- matrices
- cálculos estadísticos
- operaciones matemáticas sobre grandes volúmenes de datos

NumPy permite realizar estas operaciones **de manera rápida y eficiente**.


- Ver doc en https://numpy.org/doc/stable/reference/arrays.ndarray.html
- Algunos tipos de numpy: https://wesmckinney.com/book/numpy-basics#tbl-table_array_dtypes

## IMPORTACIÓN
Por convención NumPy se importa como np.

In [ ]:
import numpy as np

## Listas

In [ ]:
# Array de NumPy
array = np.array([1,2,3,4])

Listas de Python vs Arrays de NumPy

In [ ]:
# Lista de Python
lista = [1,2,3,4]

print(lista)
print(array)

[1, 2, 3, 4]
[1 2 3 4]


**Las listas** son flexibles y pueden tener distintos tipos de datos

**Los arrays NumPy** contienen un solo tipo de dato y están optimizados para cálculo.

#OPERACIONES MATEMÁTICAS
## Operaciones vectorizadas

Una gran ventaja de NumPy es que permite aplicar operaciones matemáticas sobre todos los elementos de un array **sin utilizar bucles**.

In [ ]:
datos = np.array([10,20,30,40])

print(datos + 5)
print(datos * 2)

[15 25 35 45]
[20 40 60 80]


## Arrays multidimensionales

En Ciencia de Datos muchas veces trabajamos con matrices.

Por ejemplo:

- filas → observaciones
- columnas → variables

In [ ]:
matriz = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(matriz)

[[10 20 30]
 [40 50 60]]


## PROPIEDADES DEL ARRAY

In [ ]:
print("Dimensiones:", matriz.ndim)
print("Forma:", matriz.shape)
print("Cantidad de elementos:", matriz.size)

Dimensiones: 2
Forma: (2, 3)
Cantidad de elementos: 6


Explicación:

ndim → número de dimensiones

shape → tamaño de la matriz

size → cantidad total de elementos

## Funciones estadísticas

NumPy incluye muchas funciones para análisis de datos.

In [ ]:
ventas = np.array([100, 120, 150, 90, 200])

print("Promedio:", ventas.mean())
print("Suma:", ventas.sum())
print("Valor máximo:", ventas.max())
print("Valor mínimo:", ventas.min())

Promedio: 132.0
Suma: 660
Valor máximo: 200
Valor mínimo: 90


## Operaciones


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5, 6])

arr2 = np.array([10, 20, 30, 40, 50, 60])

In [ ]:
# operaciones con valores
arr1 + 10

array([11, 12, 13, 14, 15, 16])

In [ ]:
# operaciones con valores
arr1 * 2

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
# operaciones con otras arrays

arr1 + arr2

array([11, 22, 33, 44, 55, 66])

In [ ]:
# podemos compararlos
arr1 > arr2

array([False, False, False, False, False, False])

# INDEXACIÓN
## Acceso a elementos

In [ ]:
ventas = np.array([100,120,150,90,200])

print(ventas[0])
print(ventas[2])

100
150


In [ ]:
# los numpy arrays se pueden modificar con slices
ventas[1:2] = 0
ventas

array([100,   0, 150,  90, 200])

## Conclusión

NumPy permite trabajar con datos numéricos de forma rápida y eficiente.

Es la base matemática de muchas herramientas de Ciencia de Datos.

En la próxima píldora veremos **Pandas**, una librería que permite trabajar con datos estructurados en forma de tablas.